- id: unit_tests
  name: unittests
  description: Runs unit tests
  entry: pwd && ./gradlew test
  pass_filenames: false
  language: system

- id: build
  name: build
  description: Building App
  entry: pwd && ./gradlew assembleDebug
  pass_filenames: false
  language: system
