- id: ktlint
  name: ktlint
  description: Runs ktlint
  entry: cd OCCMundial/ && ./gradlew ktlintFormat
  pass_filenames: false
  language: system

- id: unit_tests
  name: unittests
  description: Runs unit tests
  entry: cd OCCMundial/ && ./gradlew test
  pass_filenames: false
  language: system

- id: build
  name: build
  description: Building App
  entry: cd OCCMundial/ && ./gradlew assembleDebug
  pass_filenames: false
  language: system
